version: 0.2

env:
  parameter-store:
    DOCKER_USERNAME: "DOCKER_USERNAME"
    DOCKER_PASSWORD: "DOCKER_PASSWORD"

phases:
  build:
    commands:
      - docker build -t git.systementor.se/yacloud/cowsay0325 .
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD https://git.systementor.se
      - docker push git.systementor.se/yacloud/cowsay0325 

