version: 0.2

phases:
  build:
    commands:
      - docker build -t git.systementor.se/yacloud/cowsay0325 .
      - docker login -u yacloud -p yacloud1 https://git.systementor.se
      - docker push git.systementor.se/yacloud/cowsay0235 