# test
# docker build
# docker login
# docker push

# AWS CodeBuild - command line commandon, ls, docker build

# Github Actions - kan köra command line commandon
#                - flora av komponenter som man kan använda

name: Stefans Docker Image Creation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      with:
        image: git.systementor.se/yacloud/cowsay0325
        tags: latest
        registry: git.systementor.se
        dockerfile: Dockerfile
        username: yacloud
        password: yacloud1
